import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { applyRateLimit } from "@/lib/api-middleware";
import { RateLimitPresets } from "@/lib/rate-limit-redis";

export const dynamic = "force-dynamic";

/**
 * GET /api/meetings - List meetings with team isolation
 * Query params: startDate, endDate (optional ISO strings for date range filtering)
 */
export async function GET(request: NextRequest) {
  try {
    const rate = await applyRateLimit(request, RateLimitPresets.relaxed);
    if (!rate.success) return rate.response!;

    const supabase = await createClient();

    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Get user's team and role for team isolation
    const { data: currentUser } = await supabase
      .from("users")
      .select("team_id, role")
      .eq("id", user.id)
      .single();

    // Build query
    let query = supabase
      .from("meetings")
      .select("*")
      .order("meeting_date", { ascending: true });

    // Team isolation: only admin/management/programmer see all
    const hasGlobalAccess =
      currentUser?.role &&
      ["admin", "management", "programmer"].includes(currentUser.role);
    if (!hasGlobalAccess && currentUser?.team_id) {
      query = query.eq("team_id", currentUser.team_id);
    }

    // Optional date range filter
    const { searchParams } = new URL(request.url);
    const startDate = searchParams.get("startDate");
    const endDate = searchParams.get("endDate");
    if (startDate) query = query.gte("meeting_date", startDate);
    if (endDate) query = query.lte("meeting_date", endDate);

    const { data, error } = await query.limit(200);

    if (error) {
      console.error("Error fetching meetings:", error);
      return NextResponse.json(
        { error: "Failed to fetch meetings" },
        { status: 500 }
      );
    }

    return NextResponse.json({ meetings: data || [] });
  } catch (error) {
    console.error("Meetings GET error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

/**
 * POST /api/meetings - Create a new meeting (simple calendar event, no story creation)
 */
export async function POST(request: NextRequest) {
  try {
    const rate = await applyRateLimit(request, RateLimitPresets.standard);
    if (!rate.success) return rate.response!;

    const supabase = await createClient();

    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();

    // Validate required fields
    if (!body.title || !body.meeting_date) {
      return NextResponse.json(
        { error: "Title and meeting date are required" },
        { status: 400 }
      );
    }

    // Resolve user's team_id
    const { data: userProfile } = await supabase
      .from("users")
      .select("team_id")
      .eq("id", user.id)
      .single();

    let teamId = userProfile?.team_id || null;

    // Fallback: check if user is a team head
    if (!teamId) {
      const { data: ownedTeam } = await supabase
        .from("teams")
        .select("id")
        .eq("team_head_id", user.id)
        .single();

      if (ownedTeam?.id) {
        teamId = ownedTeam.id;
        await supabase
          .from("users")
          .update({ team_id: teamId })
          .eq("id", user.id);
      }
    }

    if (!teamId) {
      return NextResponse.json(
        { error: "Your account is not assigned to a team. Contact an administrator." },
        { status: 400 }
      );
    }

    // Insert meeting — meeting_id is auto-generated by trigger
    const { data: meeting, error: insertError } = await supabase
      .from("meetings")
      .insert({
        title: body.title,
        meeting_date: body.meeting_date,
        duration_minutes: body.duration_minutes || 60,
        location: body.location || null,
        notes: body.notes || null,
        agenda: body.agenda || null,
        contact_name: body.contact_name || null,
        contact_email: body.contact_email || null,
        contact_phone: body.contact_phone || null,
        contact_type: body.contact_type || null,
        attendees: body.attendees || [],
        category: body.category || null,
        status: "scheduled",
        team_id: teamId,
        created_by: user.id,
      })
      .select()
      .single();

    if (insertError) {
      console.error("Error creating meeting:", insertError);
      return NextResponse.json(
        { error: "Failed to create meeting" },
        { status: 500 }
      );
    }

    // Create notifications for team members
    try {
      const { data: teamMembers } = await supabase
        .from("users")
        .select("id, role, team_id")
        .eq("status", "active")
        .or(`team_id.eq.${teamId},role.in.(admin,management)`);

      if (teamMembers && teamMembers.length > 0) {
        const recipients = teamMembers.filter((u) => u.id !== user.id);
        if (recipients.length > 0) {
          const meetingDate = new Date(body.meeting_date);
          const formattedDate = meetingDate.toLocaleDateString("en-US", {
            month: "short",
            day: "numeric",
            year: "numeric",
          });
          const formattedTime = meetingDate.toLocaleTimeString("en-US", {
            hour: "numeric",
            minute: "2-digit",
            hour12: true,
          });

          const notifications = recipients.map((member) => ({
            user_id: member.id,
            type: "info",
            title: `New meeting scheduled: ${body.title}`,
            message: body.contact_name
              ? `Meeting with ${body.contact_name} on ${formattedDate} at ${formattedTime}`
              : `Meeting on ${formattedDate} at ${formattedTime}`,
            entity_type: "meeting_scheduled",
            entity_id: meeting.id,
            created_by: user.id,
            is_read: false,
          }));

          await supabase.from("notifications").insert(notifications);
        }
      }
    } catch (notifError) {
      console.error("Failed to create notifications:", notifError);
    }

    // Audit log
    try {
      await supabase.from("audit_logs").insert({
        entity_type: "meeting",
        entity_id: meeting.id,
        action: "created_meeting",
        performed_by: user.id,
        timestamp: new Date().toISOString(),
        details: {
          title: body.title,
          contact: body.contact_name,
          date: body.meeting_date,
        },
      });
    } catch (auditError) {
      console.error("Failed to create audit log:", auditError);
    }

    return NextResponse.json({ meeting }, { status: 201 });
  } catch (error) {
    console.error("Meetings POST error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
