-- Seed writers table with predefined writer names from Excel
-- Uses ON CONFLICT to skip names that already exist

INSERT INTO writers (name) VALUES
  ('Aakhtar Qayyum'),
  ('Aamir Raza'),
  ('Aamra Shahid'),
  ('Abdul Khaliq Khan'),
  ('Abida Ahmed'),
  ('Abida Manzoor Ahmed'),
  ('Abu Rashid'),
  ('Adarsh Ayaz'),
  ('Adeel Afzal'),
  ('Adeel Razzaq'),
  ('Adil Hafeez'),
  ('Adnan Sarwar'),
  ('Ali Moeen'),
  ('Ali Sikandar'),
  ('Aliya Bukhari'),
  ('Aliya Makhdoom'),
  ('Almas Khalid'),
  ('Almas-ul-Ain Khalid'),
  ('Amar Khan'),
  ('Amber Azhar'),
  ('Amjad Islam Amjad'),
  ('Amna Ahmed'),
  ('Amna Mufti'),
  ('Amna Riaz'),
  ('Aneela Syed'),
  ('Aneeza Syed'),
  ('Asif Anjum'),
  ('Asiya Mirza'),
  ('Asma Nabeel'),
  ('Asma Sayani'),
  ('Ateeq Inayat'),
  ('Ateq Inayat'),
  ('Athar Ansari'),
  ('Awais Ahmad'),
  ('Azhar Ansari'),
  ('Babar Jamal'),
  ('Bee Gul'),
  ('Bushra Ansari'),
  ('Dilawar Khan'),
  ('Dr. Muhammad Younus Butt'),
  ('Edison Idrees Masih'),
  ('Ehraaz Ali'),
  ('Erum Aftab'),
  ('Erum Wasi'),
  ('Faisal Mehmood Khan'),
  ('Faiza Iftikhar'),
  ('Fakhra Jabeen'),
  ('Fareesa Afzal'),
  ('Farhat Ishtiaq'),
  ('Farkhanda Naseem'),
  ('Fasih Bari Khan'),
  ('Fatima Faizan'),
  ('Fizza Jaffri'),
  ('Fizza Jafri'),
  ('Furqanullah Sahir'),
  ('Ghazala Aziz'),
  ('Ghazala Naqvi'),
  ('Ghulam Sabir'),
  ('Hanif Chauhan'),
  ('Haniya Javed'),
  ('Hasan Umar'),
  ('Haseeb Ahmed'),
  ('Hashim Nadeem'),
  ('Hassan Imam'),
  ('Hina Huma Nafees'),
  ('Huma Nafees'),
  ('Imran Ali Safir'),
  ('Imran Ashraf'),
  ('Imran Nazir'),
  ('Inam Hasan'),
  ('Iqbal Bano'),
  ('Iqbal Hussain'),
  ('Irfan Ahmed Shams'),
  ('Irfan Aslam'),
  ('Irfan Mughal'),
  ('Jahanzaib Qamar'),
  ('Jahanzeb Qamar'),
  ('Javeria Saud'),
  ('K Rehman'),
  ('Kanwal Mir'),
  ('Kashif Anwar'),
  ('Khalil-ur-Rehman Qamar'),
  ('Khizer Idrees'),
  ('Khurram Abbas'),
  ('Khurram Nizami'),
  ('Kifayat Rodani'),
  ('Kiran Siddiqui'),
  ('Kishore Asmal'),
  ('Madiha Shahid'),
  ('Maha Malik'),
  ('Maheen Shakeel'),
  ('Maimoona Aziz'),
  ('Maimoona Khursheed'),
  ('Malik Khuda Bakhsh'),
  ('Mamoona Aziz'),
  ('Mansoor Ahmed Khan'),
  ('Mehak Nawab'),
  ('Mehmood Elahi'),
  ('Mehmood Elai'),
  ('Mehrunnisa Mustaqeem Khan'),
  ('Mehwish Hassan'),
  ('Memona Aziz'),
  ('Mirza Asim Baig'),
  ('Misbah Ali Syed'),
  ('Misbah Nousheen'),
  ('Mohammad Asif'),
  ('Mohammad Athar Ansari'),
  ('Mohsin Ali'),
  ('Mohsin Ali Shah'),
  ('Mohsin Ejaz'),
  ('Moona Syed'),
  ('Muhammad Ahmed'),
  ('Muhammad Asif'),
  ('Muhammad Maqsood'),
  ('Mustafa Afridi'),
  ('Mustufa Hashmi'),
  ('Nabila Abar Raja'),
  ('Nadeem Ahmed'),
  ('Nadeem Asad'),
  ('Nadeem Siddique'),
  ('Nadia Ahmad'),
  ('Nadia Ahmed'),
  ('Nadia Akhtar'),
  ('Naila Ansari'),
  ('Naila Jaffri'),
  ('Nasir Hussain'),
  ('Nimra Jamil'),
  ('Noor Ul Huda Shah'),
  ('Nooran Makhdoom'),
  ('Nuzhat Saman'),
  ('Omer Ikram'),
  ('Orooj Binte Arsalan'),
  ('Osama Siddiqui'),
  ('Parisa Siddiqui'),
  ('Qaisera Hayat'),
  ('Qurat-ul-Ain Akhter'),
  ('Qurb e Abbas'),
  ('Qurban Ali Rao'),
  ('Raamis Tanveer'),
  ('Rabia Razzaque'),
  ('Radain Shah'),
  ('Rafaqat Hayat'),
  ('Rahat Jabeen'),
  ('Raheel Ahmed'),
  ('Rakshanda Rizvi'),
  ('Ramsha Raheel'),
  ('Raza Ahmed'),
  ('Rehana Aftab'),
  ('Rida Bilal'),
  ('Rizwan Ahmed'),
  ('Rizwana Haider'),
  ('Rizwana Prince'),
  ('Rubina Kabir Khan'),
  ('Rukhsana Nigar'),
  ('S. Faraz Mazhar'),
  ('Saba Hassan'),
  ('Sadia Akhtar'),
  ('Sadia Aziz Afridi'),
  ('Sadia Siddiqa'),
  ('Saima Akram Chaudhry'),
  ('Saima Wasi'),
  ('Saira Arif'),
  ('Saira Raza'),
  ('Saji Gul'),
  ('Sajjad Haider Zaidi'),
  ('Salma Younis'),
  ('Sameena Aijaz'),
  ('Sameena Ejaz'),
  ('Sameera Fazal'),
  ('Samina Tahir Butt'),
  ('Samira Faisal'),
  ('Samra Bukhari'),
  ('Sana Fahad'),
  ('Sana Zafar'),
  ('Sanam Mehdi Zaryab'),
  ('Saqib Ali Rana'),
  ('Saqlain Abbas'),
  ('Sara Sadain Syed'),
  ('Sarah Majeed'),
  ('Sarah Qayyum'),
  ('Sarwat Nazir'),
  ('Seema Ghazal'),
  ('Seema Munaf'),
  ('Seema Sheikh'),
  ('Sehrish Ali Naqvi'),
  ('Shabana Ghulam Nabi'),
  ('Shabnam Sani'),
  ('Shafia Khan'),
  ('Shafqat Khan'),
  ('Shagufta Bhatti'),
  ('Shah Yasir'),
  ('Shahid Dogar'),
  ('Shahid Nizami'),
  ('Shahzeb Khanzada'),
  ('Shakeel Arsalan'),
  ('Shazia Atta Humayun'),
  ('Shez Khan'),
  ('Shumaila Zaki'),
  ('Sidra Sehar Imran'),
  ('Sidra Tul Muntaha Jilani'),
  ('Sohail Alam Khan'),
  ('Sohail Younus'),
  ('Soofia Khurram'),
  ('Sumaira Hameed'),
  ('Suraj Baba'),
  ('Syed Ameer Ali Shah Hussaini'),
  ('Syed Mohammed Ahmed'),
  ('Syed Nabeel'),
  ('Syeda Qarsam Naseem'),
  ('Tabsir Nishat'),
  ('Tahir Nazeer'),
  ('Tanveer Malik'),
  ('Umera Ahmed'),
  ('Uzma Iftikhar'),
  ('Wajeeha Sahar'),
  ('Wajida Moin'),
  ('Wajih Warsi'),
  ('Waqas Qureshi'),
  ('Warisha Fatima'),
  ('Waseem Abbas'),
  ('Waseem Ahmed'),
  ('Wasi Shah'),
  ('Wasiq Ali'),
  ('William Pervaiz'),
  ('Yamna Ahmed'),
  ('Yasir Taj'),
  ('Yasra Rizvi'),
  ('Zafar Mairaj'),
  ('Zahid Khan'),
  ('Zanjabeel Asim Shah'),
  ('Zeeshan Haider'),
  ('Zeeshan Ilyas'),
  ('Zeeshan Junaid'),
  ('Zoha Hassan')
ON CONFLICT (name) DO NOTHING;
